# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: build
        run: |
          set -x
          go build -v ./...

      - name: test
        run: |
          set -x
          go test -v -cover ./...