name: release

on:
  #schedule:
    #- cron: '*/2 * * * *' # every 2mn
  workflow_dispatch:
    inputs:
      dry_run:
        description: "dry-run mode: if true, no git tags will be pushed."
        type: boolean
        default: false
      release_type:
        description: "Type of Release"
        required: true
        default: build
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
          - build
      forced_version:
        description: "(Optional) SemVer2-compliant forced-version to tag explicitly, instead of auto-bumping.
                      Must not already exist"
        required: false
        type: string


permissions:
  contents: read

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check if any changes since last tag
        id: check
        run: |
          git fetch --tags
          if [ -z "$(git tag --points-at HEAD)" ]; then
            echo "Nothing points at HEAD, bump a new tag"
            echo "bump=yes" >> $GITHUB_OUTPUT
          else
            echo "A tag already points to head, don't bump"
            echo "bump=no" >> $GITHUB_OUTPUT
          fi

      # Scheduled release with default values, only if there is a change
      - name: Schedule bump build version and push tag
        uses: mgreau/actions/git-bump-tag-semver@git-bump-tag-semver
        if: ${{ steps.check.outputs.bump == 'yes' && github.event_name == 'schedule' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_tag_prefix: "v"
          bump_level: "build"
          dry_run: false

      # Manual release
      - name: Manual bump version and push tag
        uses: mgreau/actions/git-bump-tag-semver@git-bump-tag-semver
        if: ${{ steps.check.outputs.bump == 'yes' && github.event_name != 'schedule' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_tag_prefix: "v"
          bump_level: ${{ inputs.release_type }}
          dry_run: ${{ inputs.dry_run }}
          forced_version: ${{ inputs.forced_version }}
